name: test stop


on:
  push:
    branches:
      - master


env:
  PUBLISH_DIR: C:\actions-runner\_work\gitPipeline\gitPipeline\myapp
  WEBSITE_DIR: E:\testSite\gitPipeline\bin\Debug\net6.0\publish
  IIS_SITE_NAME: gitPipeline


jobs:
  build-and-deploy:
    runs-on: self-hosted
    steps:

      # Stop IIS site
      - name: Stop IIS site
        shell: cmd
        run: C:\Windows\System32\inetsrv\appcmd stop site /site.name:"${{ env.IIS_SITE_NAME }}"

